#!/bin/bash
echo "Git pull"
git pull
echo "Git submodule init"
git submodule init
echo "Git submodule update"
git submodule update
git submodule foreach git pull origin master

echo "Setting up bashrc (copied from jonaz ^^)"
grep -q ". $PWD/bashrc" ~/.bashrc || echo ". $PWD/bashrc" >> ~/.bashrc

echo "Setting up dir_colors"
if [ ! -L ~/.dir_colors ]; then
    ln -s $PWD/dir_colors ~/.dir_colors
fi

if [ ! -L ~/.phpmd-ruleset.xml ]; then
	echo "Setting up phpmd xml ruleset"
    ln -s $PWD/phpmd-ruleset.xml ~/.phpmd-ruleset.xml
fi



if [ $1="force" ]; then
	echo "FORCE remove prev vim config"
	rm -r ~/.vim -rf
	rm -r ~/.vimrc -rf
	rm -r ~/.vimrc-custom -rf
fi

if [ ! -d ~/.vim/bundle/ ]; then
	mkdir -p ~/.vim/bundle
fi

if [ ! -d ~/.vim/bundle/vundle ]; then
	git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi

if [ ! -L ~/.vimrc-custom ]; then
    echo "Creating symbolic link ~/.vimrc-custom to $PWD/vimrc-custom"
    ln -s $PWD/vimrc-custom ~/.vimrc-custom
fi

if [ ! -L ~/.vimrc ]; then
    echo "Creating symbolic link ~/.vimrc to $PWD/vimrc"
    ln -s $PWD/vimrc ~/.vimrc
fi

if [ ! -d ~/.fzf ]; then
	git clone https://github.com/junegunn/fzf.git ~/.fzf
	~/.fzf/install
fi

echo "Installing plugins into vim"
vim -c 'PluginInstall' -c 'qa!'
echo "all Done!"

echo "sudo apt-get install build-essential python-dev"
echo "~/.vim/bundle/YouCompleteMe/install.sh"
~/.vim/bundle/YouCompleteMe/install.sh

#cd dot-vim
#./install
